version: 2
updates:

  - package-ecosystem: "pip"
    directory: "application/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "glean-*"
    labels:
      - "Dependabot"
      - "dependencies"
      - "application"
      - "glean-sdk"
    reviewers:
      - "mozilla/glean"
      - "hackebrot"
      - "jrbenny35"

  - package-ecosystem: "pip"
    directory: "application/"
    schedule:
      interval: "weekly"
    labels:
      - "Dependabot"
      - "dependencies"
      - "application"
    reviewers:
      - "hackebrot"
      - "jrbenny35"
    open-pull-requests-limit: 10
